### ISSUE TITLE
requires its own RTLSDR?

### ISSUE THREAD

**Issue by tedder** [fredclausen/docker-rtlsdrairband#17]
When used on a machine also running `readsb` (okay, `readsb-protobuf`), this needs access to its own RTLSDR, right? In other words, not the USB device being used for 1090 or 978.

[The basic sdr-enthusiasts example with rtlsdrairband](https://github.com/sdr-enthusiasts/docker-install/blob/main/sample-docker-compose.yml#L434) doesn't answer this.

**Comment by fredclausen** [comment]
Correct, mostly. I believe it is possible to do trickery and enable multiple different applications to use a single SDR, but it's involved and not something I've ever done. Generally, it's best to use separate SDRs.

If you want more information on that, please head over to the [discord server](https://discord.gg/sTf9uYF) and we can help you more.

**Comment by tedder** [comment]
Thanks, I thought that was the case. I lurk on the discord but will pop up at some point :)
